-- MySQL Script generated by MySQL Workbench
-- Thu Jul  1 11:09:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pruebatecnica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pruebatecnica` ;

-- -----------------------------------------------------
-- Schema pruebatecnica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pruebatecnica` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pruebatecnica` ;

-- -----------------------------------------------------
-- Table `pruebatecnica`.`activos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pruebatecnica`.`activos` ;

CREATE TABLE IF NOT EXISTS `pruebatecnica`.`activos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alto` INT NULL DEFAULT '0',
  `ancho` INT NULL DEFAULT '0',
  `descripción` VARCHAR(200) NOT NULL,
  `fecha` DATE NOT NULL,
  `largo` INT NULL DEFAULT '0',
  `name` VARCHAR(30) NOT NULL,
  `numero` VARCHAR(50) NOT NULL,
  `peso` INT NULL DEFAULT '0',
  `serial` VARCHAR(50) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `area_id` BIGINT NULL DEFAULT NULL,
  `persona_id` BIGINT NULL DEFAULT NULL,
  `tipo_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKk0a2tj3mwiaelelqgbn1ti2u6` (`area_id` ASC) VISIBLE,
  INDEX `FKbj828at1s9t6rpjexwvf2vjus` (`persona_id` ASC) VISIBLE,
  INDEX `FKscrh8nrq79mrqo6hfe3ftog2f` (`tipo_id` ASC) VISIBLE,
  INDEX `fk_activos_tipo_idx` (`tipo_id1` ASC) VISIBLE,
  INDEX `fk_activos_area1_idx` (`area_id1` ASC) VISIBLE,
  INDEX `fk_activos_persona1_idx` (`persona_id1` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pruebatecnica`.`ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pruebatecnica`.`ciudad` ;

CREATE TABLE IF NOT EXISTS `pruebatecnica`.`ciudad` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `pruebatecnica`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pruebatecnica`.`area` ;

CREATE TABLE IF NOT EXISTS `pruebatecnica`.`area` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `ciudad_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK9ykgi6ee4k2s4oy3he4bfafor` (`ciudad_id` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



-- -----------------------------------------------------
-- Table `pruebatecnica`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pruebatecnica`.`persona` ;

CREATE TABLE IF NOT EXISTS `pruebatecnica`.`persona` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(30) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pruebatecnica`.`tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pruebatecnica`.`tipo` ;

CREATE TABLE IF NOT EXISTS `pruebatecnica`.`tipo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
